// Генерує реальний PDF з даними сметы і надсилає його користувачу на email
// вкладенням через Resend. На відміну від window.print() (яке лише відкриває
// системний діалог друку), тут сервер сам будує PDF-файл і відправляє листа.

const PDFDocument = require('pdfkit');
const { Resend } = require('resend');

function buildPdfBuffer(data, zip) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'LETTER' });
    const buffers = [];
    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // ---- Header ----
    doc.fontSize(20).fillColor('#0C2340').text('StackBid', { continued: false });
    doc.fontSize(10).fillColor('#6B7A8D').text('Construction materials cost estimate');
    doc.moveDown(0.5);
    doc.fontSize(14).fillColor('#0C2340').text(data.title || 'Materials Estimate');
    doc.fontSize(10).fillColor('#6B7A8D').text(
      `ZIP ${zip || '—'} · ${data.supplier_name || '84 Lumber'} · ${data.supplier_distance || '—'}`
    );
    doc.moveDown(1);

    // ---- Table header ----
    const colX = { name: 50, qty: 280, retail: 340, wholesale: 420, local: 500 };
    doc.fontSize(9).fillColor('#9AA5B1');
    doc.text('ITEM', colX.name, doc.y);
    doc.text('QTY', colX.qty, doc.y - doc.currentLineHeight());
    doc.text('RETAIL', colX.retail, doc.y - doc.currentLineHeight());
    doc.text('WHOLESALE', colX.wholesale, doc.y - doc.currentLineHeight());
    doc.text('LOCAL', colX.local, doc.y - doc.currentLineHeight());
    doc.moveDown(0.3);
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#E5E9EF').stroke();
    doc.moveDown(0.3);

    let totalRetail = 0, totalWholesale = 0, totalLocal = 0;

    (data.categories || []).forEach((cat) => {
      if (cat.name) {
        doc.fontSize(10).fillColor('#0C2340').text(cat.name, 50, doc.y);
        doc.moveDown(0.2);
      }
      (cat.items || []).forEach((item) => {
        const qty = item.qty || 0;
        const r = (item.retail_unit || 0) * qty;
        const w = (item.wholesale_unit || 0) * qty;
        const l = (item.local_unit || 0) * qty;
        totalRetail += r; totalWholesale += w; totalLocal += l;

        const nameWidth = 220;
        doc.fontSize(9);
        const nameHeight = doc.heightOfString(item.name || '', { width: nameWidth });
        const rowHeight = Math.max(nameHeight, doc.currentLineHeight());

        if (doc.y + rowHeight > 700) doc.addPage();

        const y = doc.y;
        doc.fillColor('#0C2340').text(item.name || '', colX.name, y, { width: nameWidth });
        doc.text(String(qty) + ' ' + (item.unit || ''), colX.qty, y);
        doc.text('$' + r.toFixed(0), colX.retail, y);
        doc.text('$' + w.toFixed(0), colX.wholesale, y);
        doc.text('$' + l.toFixed(0), colX.local, y);

        doc.y = y + rowHeight + 6; // фіксований невеликий відступ між рядками
      });
    });

    doc.moveDown(0.5);
    doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#0C2340').stroke();
    doc.moveDown(0.4);
    doc.fontSize(11).fillColor('#0C2340');
    doc.text(`Total (retail): $${totalRetail.toFixed(0)}`, 50, doc.y);
    doc.text(`Total (wholesale): $${totalWholesale.toFixed(0)}`, 50, doc.y);
    doc.text(`Total (local supplier): $${totalLocal.toFixed(0)}`, 50, doc.y);
    doc.moveDown(1);
    doc.fontSize(9).fillColor('#9AA5B1').text(
      'Generated by StackBid — stackbid.app. Prices are estimates based on recent supplier data and may vary.'
    );

    doc.end();
  });
}

exports.handler = async (event) => {
  const cors = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST,OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  };
  if (event.httpMethod === 'OPTIONS') return { statusCode: 204, headers: cors, body: '' };

  try {
    const { email, estimate, zip } = JSON.parse(event.body || '{}');

    if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      return { statusCode: 400, headers: { ...cors, 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Invalid email' }) };
    }
    if (!estimate) {
      return { statusCode: 400, headers: { ...cors, 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Missing estimate data' }) };
    }

    const pdfBuffer = await buildPdfBuffer(estimate, zip);

    const resend = new Resend(process.env.RESEND_API_KEY);
    await resend.emails.send({
      from: 'StackBid <hello@stackbid.app>',
      to: email,
      subject: `Your StackBid estimate${estimate.title ? ': ' + estimate.title : ''}`,
      html: `<p>Hi,</p><p>Here's the materials estimate you requested from StackBid — attached as a PDF.</p><p>Thanks for using StackBid!</p>`,
      attachments: [
        {
          filename: 'stackbid-estimate.pdf',
          content: pdfBuffer,
        },
      ],
    });

    return { statusCode: 200, headers: { ...cors, 'Content-Type': 'application/json' }, body: JSON.stringify({ success: true }) };
  } catch (err) {
    console.error('email-pdf error:', err);
    return { statusCode: 500, headers: { ...cors, 'Content-Type': 'application/json' }, body: JSON.stringify({ error: err.message }) };
  }
};
